"""
This type stub file was generated by pyright.
"""

from pythonosc import osc_message
from typing import List, Tuple, Union

"""Build OSC messages for client applications."""

class BuildError(Exception):
    """Error raised when an incomplete message is trying to be built."""

    ...

class OscMessageBuilder:
    """Builds arbitrary OscMessage instances."""

    ARG_TYPE_FLOAT = ...
    ARG_TYPE_DOUBLE = ...
    ARG_TYPE_INT = ...
    ARG_TYPE_INT64 = ...
    ARG_TYPE_STRING = ...
    ARG_TYPE_BLOB = ...
    ARG_TYPE_RGBA = ...
    ARG_TYPE_MIDI = ...
    ARG_TYPE_TRUE = ...
    ARG_TYPE_FALSE = ...
    ARG_TYPE_NIL = ...
    ARG_TYPE_ARRAY_START = ...
    ARG_TYPE_ARRAY_STOP = ...
    _SUPPORTED_ARG_TYPES = ...
    def __init__(self, address: str = ...) -> None:
        """Initialize a new builder for a message.

        Args:
          - address: The osc address to send this message to.
        """
        ...
    @property
    def address(self) -> str:
        """Returns the OSC address this message will be sent to."""
        ...
    @address.setter
    def address(self, value: str) -> None:
        """Sets the OSC address this message will be sent to."""
        ...
    @property
    def args(
        self,
    ) -> List[Tuple[str, Union[str, bytes, bool, int, float, tuple, list]]]:
        """Returns the (type, value) arguments list of this message."""
        ...
    def add_arg(
        self,
        arg_value: Union[str, bytes, bool, int, float, tuple, list],
        arg_type: str = ...,
    ) -> None:
        """Add a typed argument to this message.

        Args:
          - arg_value: The corresponding value for the argument.
          - arg_type: A value in ARG_TYPE_* defined in this class,
                      if none then the type will be guessed.
        Raises:
          - ValueError: if the type is not supported.
        """
        ...
    def build(self) -> osc_message.OscMessage:
        """Builds an OscMessage from the current state of this builder.

        Raises:
          - BuildError: if the message could not be build or if the address
                        was empty.

        Returns:
          - an osc_message.OscMessage instance.
        """
        ...
