"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterator, List

"""Representation of an OSC message in a pythonesque way."""

class ParseError(Exception):
    """Base exception raised when a datagram parsing error occurs."""

    ...

class OscMessage:
    """Representation of a parsed datagram representing an OSC message.

    An OSC message consists of an OSC Address Pattern followed by an OSC
    Type Tag String followed by zero or more OSC Arguments.
    """

    def __init__(self, dgram: bytes) -> None: ...
    @property
    def address(self) -> str:
        """Returns the OSC address regular expression."""
        ...
    @staticmethod
    def dgram_is_message(dgram: bytes) -> bool:
        """Returns whether this datagram starts as an OSC message."""
        ...
    @property
    def size(self) -> int:
        """Returns the length of the datagram for this message."""
        ...
    @property
    def dgram(self) -> bytes:
        """Returns the datagram from which this message was built."""
        ...
    @property
    def params(self) -> List[Any]:
        """Convenience method for list(self) to get the list of parameters."""
        ...
    def __iter__(self) -> Iterator[float]:
        """Returns an iterator over the parameters of this message."""
        ...
