"""
This type stub file was generated by pyright.
"""

"""Parsing and conversion of NTP dates contained in datagrams."""
IMMEDIATELY = ...
_NTP_TIMESTAMP_TO_SECONDS = 1 / 2 ** 32
_SECONDS_TO_NTP_TIMESTAMP = 2 ** 32
_SYSTEM_EPOCH = ...
_NTP_EPOCH = ...
_NTP_DELTA = ...
Timestamp = ...

class NtpError(Exception):
    """Base class for ntp module errors."""

    ...

def parse_timestamp(timestamp: int) -> Timestamp:
    """Parse NTP timestamp as Timetag."""
    ...

def ntp_to_system_time(timestamp: bytes) -> float:
    """Convert a NTP timestamp to system time in seconds."""
    ...

def system_time_to_ntp(seconds: float) -> bytes:
    """Convert a system time in seconds to NTP timestamp."""
    ...

def ntp_time_to_system_epoch(seconds: float) -> float:
    """Convert a NTP time in seconds to system time in seconds."""
    ...

def system_time_to_ntp_epoch(seconds: float) -> float:
    """Convert a system time in seconds to NTP time in seconds."""
    ...
